# ------------------------------------------
# Project output variables

execute:
  enabled: true
  # echo: false # this is global, use "#| echo: true" for a given cell
  warning: false # false stops rendering on warnings
  message: true
  error: false # false stops rendering on errors
  debug: false

project:
  output-dir: _report_outputs/
  # resources: _report_outputs/ # makes tatic copies of images and external files, not needed for PDF only outputs

lang: es
toc-title: "Tabla de contenidos"
# bibliography: SIAP_references.bib

metadata:
  crossref: true  # Enables table and figure cross-referencing

meta:
  extended_report: true # execute extended report, customised based on basic qmd, see block, needs 'when-meta'
                         # https://quarto.org/docs/authoring/conditional.html#matching-against-metadata
  extended_appendices: true

format:
  pdf:
    documentclass: article
    header-includes:
      - \input{resources/pdf/preamble.tex}
    tbl-pos: "H"
    keep-tex: true  # Helpful for debugging

# Dynamic variables (qmd md style, could also be r params where e.g. params$a_param):
tipo_plantilla: "Ordinario - Médicos"
quincena: "17 del 2024"
responsable: "Unidad de Educación e Investigación en Salud"
contacto_1: "antonio.berlanga@imss.gob.mx; rosana.pelayo@imss.gob.mx"
date: ""

# ------------------------------------------
