# ------------------------------------------
# Project output variables

execute:
  enabled: true
  # echo: false # this is global, use "#| echo: true" for a given cell
  warning: true # false stops rendering on warnings
  message: true
  error: false # false stops rendering on errors
  debug: false

project:
  output-dir: _report_outputs/
  resources: _report_outputs/

lang: es
toc-title: "Tabla de contenidos"

metadata:
  crossref: true  # Enables table and figure cross-referencing

format:
  pdf:
    documentclass: article
    header-includes:
      - \input{resources/pdf/preamble.tex}
    tbl-pos: "H"
    fig-cap-location: bottom
    fig-prefix: "({{fig}})"  # Auto-generates (a), (b), etc.
    keep-tex: true  # Helpful for debugging

# Dynamic variables (qmd md style, could also be r params where e.g. params$a_param):
tipo_plantilla: "Ordinaria"
quincena: "17 del 2024"
responsable: "Unidad de Educación e Investigación en Salud"
contacto_1: "rosana.pelayo@imss.gob.mx; antonio.berlanga@imss.gob.mx"
date: ""
# ------------------------------------------
