# ------------------------------------------
# Project output variables

execute:
  enabled: true
  echo: false # this is global, use "#| echo: true" for a given cell
  warning: true
  message: true
  error: true
  debug: false

# margin: 0
# fig-width: 7.5
# number-sections: true
# bibliography: references.bib

project:
  output-dir: _report_outputs/
  resources: _report_outputs/

lang: es
toc-title: "Tabla de contenidos"

format:
  pdf:
    # toc: true
    # toc-depth: 2
    number_sections: true
    documentclass: article
    header-includes:
      - \input{resources/pdf/preamble.tex}


# Dynamic variables (qmd md style, could also be r params where e.g. params$a_param):
#report_title: "Análisis de la administración del personal"
#report_subtitle: "SIAP - IMSS"
tipo_plantilla: "Ordinaria"
quincena: "17 del 2024"
pers_1: "Antonio J Berlanga Taylor"
contacto_1: "antonio.berlanga@imss.gob.mx"
date: ""
# ------------------------------------------
