name: Python and R CI with Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: ${{ matrix.language }} tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        language: [python, r]

    steps:
      - uses: actions/checkout@v4

      # Set up Python:
      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Set up R:
      - name: Set up R
        if: matrix.language == 'r'
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install R dependencies (from r-requirements.txt):
      - name: Install R dependencies
        if: matrix.language == 'r'
        run: |
          if [ -f r-requirements.txt ]; then
            pkgs=$(grep -v '^#' r-requirements.txt | grep -v '^$' | tr '\n' ' ')
            Rscript -e "install.packages(strsplit(Sys.getenv('PKGS'), ' ')[[1]], repos='https://cloud.r-project.org', dependencies=TRUE)" PKGS="$pkgs"
          fi

      # Install Python dependencies:
      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      # Run R tests and measure coverage (data science project, not a package):
      - name: Run R tests with coverage
        if: matrix.language == 'r'
        run: |
          Rscript -e "if (!requireNamespace('covr', quietly=TRUE)) install.packages('covr', repos='https://cloud.r-project.org')"
          Rscript -e "if (!requireNamespace('testthat', quietly=TRUE)) install.packages('testthat', repos='https://cloud.r-project.org')"
          Rscript -e "cov <- covr::file_coverage('tests/testthat/testthat.R', list.files('R', full.names=TRUE, pattern=\"\\\\\\.R$\")); covr::to_cobertura(cov)"
        shell: bash
# Third line can cause escape hell, try otherwise: Rscript -e "pattern = \"\\\\.R$\"; cov <- covr::file_coverage('tests/testthat/testthat.R', list.files('R', full.names=TRUE, pattern=pattern)); covr::to_cobertura(cov)"


      # Run Python tests and measure coverage:
      - name: Run Python tests with coverage
        if: matrix.language == 'python'
        run: |
          pytest --cov=. --cov-report=xml

      # Upload R coverage to Codecov:
      - name: Upload R coverage to Codecov
        if: matrix.language == 'r' && hashFiles('cobertura.xml') != ''
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: cobertura.xml
          flags: r

      # Upload Python coverage to Codecov:
      - name: Upload Python coverage to Codecov
        if: matrix.language == 'python' && hashFiles('coverage.xml') != ''
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          flags: python
