name: Python-CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: ~/.R/library
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install R packages from file # otherwise: Rscript -e "install.packages(c('testthat'), repos='https://cloud.r-project.org')"
        run: |
          Rscript -e "pkgs <- scan('r-requirements.txt', what=character()); install.packages(pkgs, repos='https://cloud.r-project.org')"

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: ludeeus/action-shellcheck@v2
        with:
          scandir: oferta_educativa_laboral/pipeline/scripts

      - name: Run flake8
        run: flake8 .

      - name: Run tests
        run: coverage run -m pytest && coverage report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: antoniojbt/oferta_educativa_laboral
        continue-on-error: true
            
