name: CI/CD test coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # --- R setup & dependencies ---
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        
        - name: Install R dependencies from list (CRAN + GitHub)
        run: |
         Rscript -e '
         repos <- "https://packagemanager.rstudio.com/all/latest"
         reqs  <- scan("r-requirements.txt", what = "character", comment.char = "#")
         # split CRAN vs GitHub
         cran  <- reqs[!grepl("^github::", reqs)]
         gh    <- sub("^github::", "", reqs[ grepl("^github::", reqs) ])
         if (length(cran) > 0)
         install.packages(cran, repos = repos, dependencies = TRUE)
         if (length(gh) > 0) {
         if (!requireNamespace("remotes", quietly = TRUE))
           install.packages("remotes", repos = repos)
         remotes::install_github(gh)
         }
         '

      - name: Test coverage
        run: |
          cov <- covr::package_coverage(
            quiet = FALSE,
            clean = FALSE,
            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
          )
          covr::to_cobertura(cov)
        shell: Rscript {0}

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: ${{ github.event_name != 'pull_request' && true || false }}
          file: ./cobertura.xml
          plugin: noop
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Show testthat output
        if: always()
        run: |
          ## --------------------------------------------------------------------
          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test-failures
          path: ${{ runner.temp }}/package

      # --- Python setup & dependencies ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          
      - name: Run Python tests and coverage
        run: |
          pytest --cov --cov-branch --cov-report=xml

      # --- Upload coverage to Codecov ---
      - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
          slug: antoniojbt/oferta_educativa_laboral
