name: CI/CD test coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # --- R setup & dependencies ---
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install R dependencies from list
        run: |
         Rscript -e 'repos <- "https://packagemanager.rstudio.com/all/latest"
         pkgs  <- scan("r-requirements.txt", what = "character")
         install.packages(pkgs, repos = repos)
         '

      - name: Run R coverage and export XML
        run: |
          Rscript -e "covr::report(type='cobertura', file='coverage-r.xml')"


      # --- Python setup & dependencies ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run Python tests and coverage
        run: |
          pytest --cov=your_python_package --cov-report=xml --cov-report=term

      # --- Upload coverage to Codecov ---
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml, coverage-r.xml
          flags: python, r
